workflows:
  android-apk:
    name: Mi Jornada - Android APK
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      java: 17
    scripts:
      - name: Actualizar Gradle automaticamente
        script: |
          find . -name "gradle-wrapper.properties" -exec sed -i '' 's/8.7/8.9/g' {} + || true
          chmod +x ./gradlew
      - name: Construir APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
