workflows:
  android-apk:
    name: Mi Jornada - Android APK
    instance_type: linux_x2
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "com.nico.mijornada"
      groups:
        - google_play
      java: 17
    scripts:
      - name: Check project
        script: |
          chmod +x ./gradlew
          ./gradlew --version
      - name: Build release APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
